from pyspark import pipelines as dp

# Curated IOC/ISO-3166 mapping for the 3-letter codes present in the source data.
# Drafted with LLM help for the long tail, then cross-checked against the public
# IOC code table. Extend if silver surfaces a code not covered here.
COUNTRY_MAPPING = [
    # code,   name,                      iso_a2, iso_a3, region,     subregion
    ("AFG", "Afghanistan",               "AF", "AFG", "Asia",     "Southern Asia"),
    ("ALB", "Albania",                   "AL", "ALB", "Europe",   "Southern Europe"),
    ("ALG", "Algeria",                   "DZ", "DZA", "Africa",   "Northern Africa"),
    ("AND", "Andorra",                   "AD", "AND", "Europe",   "Southern Europe"),
    ("ANG", "Angola",                    "AO", "AGO", "Africa",   "Middle Africa"),
    ("ARG", "Argentina",                 "AR", "ARG", "Americas", "South America"),
    ("ARM", "Armenia",                   "AM", "ARM", "Asia",     "Western Asia"),
    ("ARU", "Aruba",                     "AW", "ABW", "Americas", "Caribbean"),
    ("AUS", "Australia",                 "AU", "AUS", "Oceania",  "Australia and New Zealand"),
    ("AUT", "Austria",                   "AT", "AUT", "Europe",   "Western Europe"),
    ("AZE", "Azerbaijan",                "AZ", "AZE", "Asia",     "Western Asia"),
    ("BAH", "Bahamas",                   "BS", "BHS", "Americas", "Caribbean"),
    ("BAR", "Barbados",                  "BB", "BRB", "Americas", "Caribbean"),
    ("BDI", "Burundi",                   "BI", "BDI", "Africa",   "Eastern Africa"),
    ("BEL", "Belgium",                   "BE", "BEL", "Europe",   "Western Europe"),
    ("BEN", "Benin",                     "BJ", "BEN", "Africa",   "Western Africa"),
    ("BER", "Bermuda",                   "BM", "BMU", "Americas", "Northern America"),
    ("BHU", "Bhutan",                    "BT", "BTN", "Asia",     "Southern Asia"),
    ("BIH", "Bosnia and Herzegovina",    "BA", "BIH", "Europe",   "Southern Europe"),
    ("BLR", "Belarus",                   "BY", "BLR", "Europe",   "Eastern Europe"),
    ("BOL", "Bolivia",                   "BO", "BOL", "Americas", "South America"),
    ("BOT", "Botswana",                  "BW", "BWA", "Africa",   "Southern Africa"),
    ("BRA", "Brazil",                    "BR", "BRA", "Americas", "South America"),
    ("BRN", "Bahrain",                   "BH", "BHR", "Asia",     "Western Asia"),
    ("BUL", "Bulgaria",                  "BG", "BGR", "Europe",   "Eastern Europe"),
    ("BUR", "Burkina Faso",              "BF", "BFA", "Africa",   "Western Africa"),
    ("CAM", "Cambodia",                  "KH", "KHM", "Asia",     "South-eastern Asia"),
    ("CAN", "Canada",                    "CA", "CAN", "Americas", "Northern America"),
    ("CHA", "Chad",                      "TD", "TCD", "Africa",   "Middle Africa"),
    ("CHI", "Chile",                     "CL", "CHL", "Americas", "South America"),
    ("CHN", "China",                     "CN", "CHN", "Asia",     "Eastern Asia"),
    ("CIV", "Côte d'Ivoire",             "CI", "CIV", "Africa",   "Western Africa"),
    ("CMR", "Cameroon",                  "CM", "CMR", "Africa",   "Middle Africa"),
    ("COD", "DR Congo",                  "CD", "COD", "Africa",   "Middle Africa"),
    ("COL", "Colombia",                  "CO", "COL", "Americas", "South America"),
    ("CRC", "Costa Rica",                "CR", "CRI", "Americas", "Central America"),
    ("CRO", "Croatia",                   "HR", "HRV", "Europe",   "Southern Europe"),
    ("CUB", "Cuba",                      "CU", "CUB", "Americas", "Caribbean"),
    ("CYP", "Cyprus",                    "CY", "CYP", "Asia",     "Western Asia"),
    ("CZE", "Czechia",                   "CZ", "CZE", "Europe",   "Eastern Europe"),
    ("DEN", "Denmark",                   "DK", "DNK", "Europe",   "Northern Europe"),
    ("DJI", "Djibouti",                  "DJ", "DJI", "Africa",   "Eastern Africa"),
    ("DMA", "Dominica",                  "DM", "DMA", "Americas", "Caribbean"),
    ("DOM", "Dominican Republic",        "DO", "DOM", "Americas", "Caribbean"),
    ("ECU", "Ecuador",                   "EC", "ECU", "Americas", "South America"),
    ("EGY", "Egypt",                     "EG", "EGY", "Africa",   "Northern Africa"),
    ("ERI", "Eritrea",                   "ER", "ERI", "Africa",   "Eastern Africa"),
    ("ESA", "El Salvador",               "SV", "SLV", "Americas", "Central America"),
    ("ESP", "Spain",                     "ES", "ESP", "Europe",   "Southern Europe"),
    ("EST", "Estonia",                   "EE", "EST", "Europe",   "Northern Europe"),
    ("ETH", "Ethiopia",                  "ET", "ETH", "Africa",   "Eastern Africa"),
    ("FIJ", "Fiji",                      "FJ", "FJI", "Oceania",  "Melanesia"),
    ("FIN", "Finland",                   "FI", "FIN", "Europe",   "Northern Europe"),
    ("FRA", "France",                    "FR", "FRA", "Europe",   "Western Europe"),
    ("GBR", "United Kingdom",            "GB", "GBR", "Europe",   "Northern Europe"),
    ("GEO", "Georgia",                   "GE", "GEO", "Asia",     "Western Asia"),
    ("GER", "Germany",                   "DE", "DEU", "Europe",   "Western Europe"),
    ("GHA", "Ghana",                     "GH", "GHA", "Africa",   "Western Africa"),
    ("GRE", "Greece",                    "GR", "GRC", "Europe",   "Southern Europe"),
    ("GUA", "Guatemala",                 "GT", "GTM", "Americas", "Central America"),
    ("HKG", "Hong Kong",                 "HK", "HKG", "Asia",     "Eastern Asia"),
    ("HON", "Honduras",                  "HN", "HND", "Americas", "Central America"),
    ("HUN", "Hungary",                   "HU", "HUN", "Europe",   "Eastern Europe"),
    ("INA", "Indonesia",                 "ID", "IDN", "Asia",     "South-eastern Asia"),
    ("IND", "India",                     "IN", "IND", "Asia",     "Southern Asia"),
    ("IRI", "Iran",                      "IR", "IRN", "Asia",     "Southern Asia"),
    ("IRL", "Ireland",                   "IE", "IRL", "Europe",   "Northern Europe"),
    ("IRQ", "Iraq",                      "IQ", "IRQ", "Asia",     "Western Asia"),
    ("ISL", "Iceland",                   "IS", "ISL", "Europe",   "Northern Europe"),
    ("ISR", "Israel",                    "IL", "ISR", "Asia",     "Western Asia"),
    ("ITA", "Italy",                     "IT", "ITA", "Europe",   "Southern Europe"),
    ("JAM", "Jamaica",                   "JM", "JAM", "Americas", "Caribbean"),
    ("JOR", "Jordan",                    "JO", "JOR", "Asia",     "Western Asia"),
    ("JPN", "Japan",                     "JP", "JPN", "Asia",     "Eastern Asia"),
    ("KAZ", "Kazakhstan",                "KZ", "KAZ", "Asia",     "Central Asia"),
    ("KEN", "Kenya",                     "KE", "KEN", "Africa",   "Eastern Africa"),
    ("KGZ", "Kyrgyzstan",                "KG", "KGZ", "Asia",     "Central Asia"),
    ("KOR", "South Korea",               "KR", "KOR", "Asia",     "Eastern Asia"),
    ("KSA", "Saudi Arabia",              "SA", "SAU", "Asia",     "Western Asia"),
    ("KUW", "Kuwait",                    "KW", "KWT", "Asia",     "Western Asia"),
    ("LAO", "Laos",                      "LA", "LAO", "Asia",     "South-eastern Asia"),
    ("LAT", "Latvia",                    "LV", "LVA", "Europe",   "Northern Europe"),
    ("LBA", "Libya",                     "LY", "LBY", "Africa",   "Northern Africa"),
    ("LBN", "Lebanon",                   "LB", "LBN", "Asia",     "Western Asia"),
    ("LBR", "Liberia",                   "LR", "LBR", "Africa",   "Western Africa"),
    ("LCA", "Saint Lucia",               "LC", "LCA", "Americas", "Caribbean"),
    ("LIE", "Liechtenstein",             "LI", "LIE", "Europe",   "Western Europe"),
    ("LTU", "Lithuania",                 "LT", "LTU", "Europe",   "Northern Europe"),
    ("LUX", "Luxembourg",                "LU", "LUX", "Europe",   "Western Europe"),
    ("MAD", "Madagascar",                "MG", "MDG", "Africa",   "Eastern Africa"),
    ("MAR", "Morocco",                   "MA", "MAR", "Africa",   "Northern Africa"),
    ("MAS", "Malaysia",                  "MY", "MYS", "Asia",     "South-eastern Asia"),
    ("MAW", "Malawi",                    "MW", "MWI", "Africa",   "Eastern Africa"),
    ("MDA", "Moldova",                   "MD", "MDA", "Europe",   "Eastern Europe"),
    ("MEX", "Mexico",                    "MX", "MEX", "Americas", "Central America"),
    ("MGL", "Mongolia",                  "MN", "MNG", "Asia",     "Eastern Asia"),
    ("MKD", "North Macedonia",           "MK", "MKD", "Europe",   "Southern Europe"),
    ("MLI", "Mali",                      "ML", "MLI", "Africa",   "Western Africa"),
    ("MLT", "Malta",                     "MT", "MLT", "Europe",   "Southern Europe"),
    ("MNE", "Montenegro",                "ME", "MNE", "Europe",   "Southern Europe"),
    ("MOZ", "Mozambique",                "MZ", "MOZ", "Africa",   "Eastern Africa"),
    ("MRI", "Mauritius",                 "MU", "MUS", "Africa",   "Eastern Africa"),
    ("MYA", "Myanmar",                   "MM", "MMR", "Asia",     "South-eastern Asia"),
    ("NAM", "Namibia",                   "NA", "NAM", "Africa",   "Southern Africa"),
    ("NCA", "Nicaragua",                 "NI", "NIC", "Americas", "Central America"),
    ("NED", "Netherlands",               "NL", "NLD", "Europe",   "Western Europe"),
    ("NEP", "Nepal",                     "NP", "NPL", "Asia",     "Southern Asia"),
    ("NGR", "Nigeria",                   "NG", "NGA", "Africa",   "Western Africa"),
    ("NIG", "Niger",                     "NE", "NER", "Africa",   "Western Africa"),
    ("NOR", "Norway",                    "NO", "NOR", "Europe",   "Northern Europe"),
    ("NZL", "New Zealand",               "NZ", "NZL", "Oceania",  "Australia and New Zealand"),
    ("OMA", "Oman",                      "OM", "OMN", "Asia",     "Western Asia"),
    ("PAK", "Pakistan",                  "PK", "PAK", "Asia",     "Southern Asia"),
    ("PAN", "Panama",                    "PA", "PAN", "Americas", "Central America"),
    ("PAR", "Paraguay",                  "PY", "PRY", "Americas", "South America"),
    ("PER", "Peru",                      "PE", "PER", "Americas", "South America"),
    ("PHI", "Philippines",               "PH", "PHL", "Asia",     "South-eastern Asia"),
    ("POL", "Poland",                    "PL", "POL", "Europe",   "Eastern Europe"),
    ("POR", "Portugal",                  "PT", "PRT", "Europe",   "Southern Europe"),
    ("PUR", "Puerto Rico",               "PR", "PRI", "Americas", "Caribbean"),
    ("QAT", "Qatar",                     "QA", "QAT", "Asia",     "Western Asia"),
    ("ROU", "Romania",                   "RO", "ROU", "Europe",   "Eastern Europe"),
    ("RSA", "South Africa",              "ZA", "ZAF", "Africa",   "Southern Africa"),
    ("RUS", "Russia",                    "RU", "RUS", "Europe",   "Eastern Europe"),
    ("RWA", "Rwanda",                    "RW", "RWA", "Africa",   "Eastern Africa"),
    ("SEN", "Senegal",                   "SN", "SEN", "Africa",   "Western Africa"),
    ("SIN", "Singapore",                 "SG", "SGP", "Asia",     "South-eastern Asia"),
    ("SLE", "Sierra Leone",              "SL", "SLE", "Africa",   "Western Africa"),
    ("SLO", "Slovenia",                  "SI", "SVN", "Europe",   "Southern Europe"),
    ("SMR", "San Marino",                "SM", "SMR", "Europe",   "Southern Europe"),
    ("SOL", "Solomon Islands",           "SB", "SLB", "Oceania",  "Melanesia"),
    ("SOM", "Somalia",                   "SO", "SOM", "Africa",   "Eastern Africa"),
    ("SRB", "Serbia",                    "RS", "SRB", "Europe",   "Southern Europe"),
    ("SRI", "Sri Lanka",                 "LK", "LKA", "Asia",     "Southern Asia"),
    ("SUI", "Switzerland",               "CH", "CHE", "Europe",   "Western Europe"),
    ("SUR", "Suriname",                  "SR", "SUR", "Americas", "South America"),
    ("SVK", "Slovakia",                  "SK", "SVK", "Europe",   "Eastern Europe"),
    ("SWE", "Sweden",                    "SE", "SWE", "Europe",   "Northern Europe"),
    ("SYR", "Syria",                     "SY", "SYR", "Asia",     "Western Asia"),
    ("TAN", "Tanzania",                  "TZ", "TZA", "Africa",   "Eastern Africa"),
    ("THA", "Thailand",                  "TH", "THA", "Asia",     "South-eastern Asia"),
    ("TJK", "Tajikistan",                "TJ", "TJK", "Asia",     "Central Asia"),
    ("TKM", "Turkmenistan",              "TM", "TKM", "Asia",     "Central Asia"),
    ("TOG", "Togo",                      "TG", "TGO", "Africa",   "Western Africa"),
    ("TPE", "Chinese Taipei",            "TW", "TWN", "Asia",     "Eastern Asia"),
    ("TRI", "Trinidad and Tobago",       "TT", "TTO", "Americas", "Caribbean"),
    ("TUN", "Tunisia",                   "TN", "TUN", "Africa",   "Northern Africa"),
    ("TUR", "Türkiye",                   "TR", "TUR", "Asia",     "Western Asia"),
    ("UAE", "United Arab Emirates",      "AE", "ARE", "Asia",     "Western Asia"),
    ("UGA", "Uganda",                    "UG", "UGA", "Africa",   "Eastern Africa"),
    ("UKR", "Ukraine",                   "UA", "UKR", "Europe",   "Eastern Europe"),
    ("URU", "Uruguay",                   "UY", "URY", "Americas", "South America"),
    ("USA", "United States",             "US", "USA", "Americas", "Northern America"),
    ("UZB", "Uzbekistan",                "UZ", "UZB", "Asia",     "Central Asia"),
    ("VEN", "Venezuela",                 "VE", "VEN", "Americas", "South America"),
    ("VIE", "Vietnam",                   "VN", "VNM", "Asia",     "South-eastern Asia"),
    ("YEM", "Yemen",                     "YE", "YEM", "Asia",     "Western Asia"),
    ("ZAM", "Zambia",                    "ZM", "ZMB", "Africa",   "Eastern Africa"),
    ("ZIM", "Zimbabwe",                  "ZW", "ZWE", "Africa",   "Eastern Africa"),
    # ISO alpha-3 codes the source data also uses (mixed with IOC):
    ("SGP", "Singapore",                 "SG", "SGP", "Asia",     "South-eastern Asia"),
    ("BRU", "Brunei",                    "BN", "BRN", "Asia",     "South-eastern Asia"),
    ("LES", "Lesotho",                   "LS", "LSO", "Africa",   "Southern Africa"),
    ("SWZ", "Eswatini",                  "SZ", "SWZ", "Africa",   "Southern Africa"),
    ("MAC", "Macao",                     "MO", "MAC", "Asia",     "Eastern Asia"),
    ("KOS", "Kosovo",                    "XK", "XKX", "Europe",   "Southern Europe"),
    ("CPV", "Cabo Verde",                "CV", "CPV", "Africa",   "Western Africa"),
    ("IVB", "British Virgin Islands",    "VG", "VGB", "Americas", "Caribbean"),
    ("MON", "Monaco",                    "MC", "MCO", "Europe",   "Western Europe"),
    ("GUY", "Guyana",                    "GY", "GUY", "Americas", "South America"),
    ("CAY", "Cayman Islands",            "KY", "CYM", "Americas", "Caribbean"),
    ("GAB", "Gabon",                     "GA", "GAB", "Africa",   "Middle Africa"),
    ("GRL", "Greenland",                 "GL", "GRL", "Americas", "Northern America"),
    ("COM", "Comoros",                   "KM", "COM", "Africa",   "Eastern Africa"),
    ("XXX", "Unknown / Stateless",       "",   "",    "Unknown",  "Unknown"),
]

COLS = ["country_code", "country_name", "iso_alpha_2", "iso_alpha_3", "region", "subregion"]


@dp.table(
    name="marathos.gold.dim_country",
    comment="Dim country - gold layer (curated IOC/ISO-3166 lookup)",
)
def dim_country():
    return spark.createDataFrame(COUNTRY_MAPPING, COLS)
