-- Databricks notebook source
-- MAGIC %md
-- MAGIC # Task 6 — Marathos dashboard queries
-- MAGIC
-- MAGIC One SQL cell per widget for the Marathos Lakeview dashboard. Each cell is
-- MAGIC structured as:
-- MAGIC
-- MAGIC - **Title** — what the widget is.
-- MAGIC - **Visuals** — recommended visualization (Counter, Bar, Line, Map, Table, Pie).
-- MAGIC - **Insight** — what story the widget tells, why it belongs on an executive
-- MAGIC   dashboard.
-- MAGIC - The SQL itself, ready to paste into a Lakeview dataset.
-- MAGIC
-- MAGIC The dashboard is built in seven sections:
-- MAGIC
-- MAGIC | Section | Theme                          | Widgets |
-- MAGIC |---------|--------------------------------|---------|
-- MAGIC | A       | Executive KPI cards            | 6       |
-- MAGIC | B       | Growth & participation trends  | 4       |
-- MAGIC | C       | Global footprint               | 3       |
-- MAGIC | D       | Athlete demographics           | 3       |
-- MAGIC | E       | Event profile                  | 4       |
-- MAGIC | F       | Performance & records          | 4       |
-- MAGIC
-- MAGIC
-- MAGIC All queries read from the gold layer (`marathos.gold.*`) — primarily the
-- MAGIC pre-joined `vw_results_enriched` view, which is the workhorse of the
-- MAGIC dashboard. The simulated events generated by the notebook flow
-- MAGIC through to gold automatically, so KPIs refresh every pipeline run.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Section A — Executive KPI cards
-- MAGIC
-- MAGIC Six headline counters that anchor the top of the dashboard. Each answers a
-- MAGIC "how big is Marathos?" question at a glance.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### A1. Total finishes
-- MAGIC **Viz:** Counter   **Insight:** Total volume of recorded athletic effort
-- MAGIC tracked by Marathos. Grows linearly with every new event ingested — a
-- MAGIC sudden jump signals a successful BONUS-stream run.

-- COMMAND ----------

SELECT COUNT(*) AS total_finishes
FROM   marathos.gold.fct_results;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### A2. Distinct athletes
-- MAGIC **Viz:** Counter   **Insight:** Size of the global ultramarathon
-- MAGIC community Marathos has visibility into. A growing gap between this and
-- MAGIC A1 (total finishes) means the typical athlete is racing more often.

-- COMMAND ----------

SELECT COUNT(*) AS distinct_athletes
FROM   marathos.gold.dim_athlete;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### A3. Distinct events
-- MAGIC **Viz:** Counter   **Insight:** Number of unique race events in the
-- MAGIC catalog. Measures the breadth of Marathos' coverage of the sport.

-- COMMAND ----------

SELECT COUNT(*) AS distinct_events
FROM   marathos.gold.dim_event;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### A4. Countries represented
-- MAGIC **Viz:** Counter   **Insight:** Geographic footprint — how globally
-- MAGIC inclusive the sport is.

-- COMMAND ----------

SELECT COUNT(DISTINCT athlete_country) AS countries_represented
FROM   marathos.gold.dim_athlete
WHERE  athlete_country IS NOT NULL;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### A5. Median 100 km finish time (hours)
-- MAGIC **Viz:** Counter   **Insight:** A robust speed benchmark. Median (not
-- MAGIC mean) is resilient to elite outliers and DNF-adjacent slow finishes,
-- MAGIC giving the "typical" 100 km finisher's time.

-- COMMAND ----------

SELECT ROUND(PERCENTILE_APPROX(performance_time_seconds, 0.5) / 3600.0, 2)
       AS median_100k_finish_hours
FROM   marathos.gold.vw_results_enriched
WHERE  event_type = 'distance'
  AND  event_distance_km BETWEEN 99 AND 101
  AND  performance_time_seconds IS NOT NULL;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### A6. Female participation rate
-- MAGIC **Viz:** Counter (percentage)   **Insight:** Tracks gender balance.
-- MAGIC Marathos sponsors can use this as a diversity-of-sport metric; a rising
-- MAGIC trend over time (see D2) is a positive signal.

-- COMMAND ----------

SELECT ROUND(
         100.0 * SUM(CASE WHEN athlete_gender = 'W' THEN 1 ELSE 0 END)
         / NULLIF(COUNT(*), 0),
         1
       ) AS female_participation_pct
FROM   marathos.gold.vw_results_enriched
WHERE  athlete_gender IN ('M', 'W');

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Section B — Growth & participation trends
-- MAGIC
-- MAGIC How participation has evolved over Marathos' two-century history.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### B1. Finishes per year
-- MAGIC **Viz:** Bar chart (event_year × n_finishes)   **Insight:** The single
-- MAGIC most-watched chart — shows the explosive growth of ultramarathon
-- MAGIC participation since the 1980s, plus any post-COVID dip and recovery.

-- COMMAND ----------

SELECT event_year, COUNT(*) AS n_finishes
FROM   marathos.gold.vw_results_enriched
GROUP  BY event_year
ORDER  BY event_year;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### B2. Year-over-year growth %
-- MAGIC **Viz:** Bar chart (event_year × yoy_growth_pct), colour by sign
-- MAGIC **Insight:** Surfaces inflection years — explosive growth seasons vs.
-- MAGIC contractions (lockdowns, recession years). Useful for board narratives:
-- MAGIC "we've seen 8 consecutive years of double-digit growth."

-- COMMAND ----------

WITH yearly AS (
  SELECT event_year, COUNT(*) AS n_finishes
  FROM   marathos.gold.vw_results_enriched
  GROUP  BY event_year
)
SELECT
  event_year,
  n_finishes,
  LAG(n_finishes) OVER (ORDER BY event_year) AS prev_year_finishes,
  ROUND(
    100.0 * (n_finishes - LAG(n_finishes) OVER (ORDER BY event_year))
    / NULLIF(LAG(n_finishes) OVER (ORDER BY event_year), 0),
    1
  ) AS yoy_growth_pct
FROM   yearly
ORDER  BY event_year;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### B3. Cumulative distinct athletes joining the sport
-- MAGIC **Viz:** Area chart (event_year × cumulative_athletes)
-- MAGIC **Insight:** Each athlete is counted in the year of their first ever
-- MAGIC recorded finish. The cumulative line is essentially "total people who
-- MAGIC have *ever* finished an ultra" by year. Slope = community recruitment
-- MAGIC rate.

-- COMMAND ----------

WITH athlete_debut AS (
  SELECT f.athlete_id, MIN(d.year) AS first_year
  FROM   marathos.gold.fct_results f
  JOIN   marathos.gold.dim_date    d USING (date_id)
  GROUP  BY f.athlete_id
)
SELECT
  first_year                                     AS event_year,
  COUNT(*)                                       AS new_athletes,
  SUM(COUNT(*)) OVER (ORDER BY first_year)       AS cumulative_athletes
FROM   athlete_debut
WHERE  first_year IS NOT NULL
GROUP  BY first_year
ORDER  BY first_year;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### B4. Top 15 events by participation
-- MAGIC **Viz:** Horizontal bar chart, sorted desc   **Insight:** The "majors"
-- MAGIC of ultramarathon. These are the events where Marathos sponsorship dollars
-- MAGIC reach the most athletes. Avg-speed column adds a difficulty signal.

-- COMMAND ----------

SELECT
  event_name,
  event_distance_length,
  COUNT(*)                              AS n_finishes,
  ROUND(AVG(athlete_average_speed), 2)  AS avg_speed_kmh
FROM   marathos.gold.vw_results_enriched
GROUP  BY event_name, event_distance_length
ORDER  BY n_finishes DESC
LIMIT  15;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Section C — Global footprint
-- MAGIC
-- MAGIC Where in the world the ultramarathon community lives.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### C1. Top 25 countries by finishes
-- MAGIC **Viz:** Choropleth map (country, n_finishes) **or** horizontal bar
-- MAGIC **Insight:** Marathos' commercial heatmap — countries to prioritise for
-- MAGIC partnership, sponsorship, and merchandise localisation. Avg speed gives
-- MAGIC a quick "are these elite athletes or weekend warriors?" signal.

-- COMMAND ----------

SELECT
  COALESCE(c.country_name, r.athlete_country) AS country,
  r.athlete_country                            AS ioc_code,
  COUNT(*)                                     AS n_finishes,
  ROUND(AVG(r.athlete_average_speed), 2)       AS avg_speed_kmh
FROM   marathos.gold.vw_results_enriched r
LEFT JOIN marathos.gold.dim_country c
       ON r.athlete_country = c.country_code
WHERE  r.athlete_country IS NOT NULL
GROUP  BY country, r.athlete_country
ORDER  BY n_finishes DESC
LIMIT  25;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### C2. Country diversity over time
-- MAGIC **Viz:** Line chart   **Insight:** Number of distinct nations finishing
-- MAGIC each year. A rising line means the sport is globalising; a plateau
-- MAGIC means it's saturated geographically.

-- COMMAND ----------

SELECT event_year,
       COUNT(DISTINCT athlete_country) AS countries_represented
FROM   marathos.gold.vw_results_enriched
WHERE  athlete_country IS NOT NULL
GROUP  BY event_year
ORDER  BY event_year;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### C3. Country leaderboard — fastest 100 km nations
-- MAGIC **Viz:** Table, sortable   **Insight:** Average 100 km finish time per
-- MAGIC country (min 50 finishers). Surfaces traditionally strong ultra nations
-- MAGIC (JPN, RUS, ZAF, USA, GER) vs. emerging ones.

-- COMMAND ----------

SELECT
  COALESCE(c.country_name, r.athlete_country)        AS country,
  COUNT(*)                                            AS n_100k_finishes,
  ROUND(AVG(r.performance_time_seconds) / 3600.0, 2)  AS avg_finish_hours,
  ROUND(MIN(r.performance_time_seconds) / 3600.0, 2)  AS fastest_finish_hours
FROM   marathos.gold.vw_results_enriched r
LEFT JOIN marathos.gold.dim_country c
       ON r.athlete_country = c.country_code
WHERE  r.event_distance_km BETWEEN 99 AND 101
  AND  r.performance_time_seconds IS NOT NULL
  AND  r.athlete_country IS NOT NULL
GROUP  BY country
HAVING COUNT(*) >= 50
ORDER  BY avg_finish_hours ASC
LIMIT  25;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Section D — Athlete demographics
-- MAGIC
-- MAGIC Who is finishing these races, and how that's changed.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### D1. Age distribution (5-year buckets)
-- MAGIC **Viz:** Histogram (column chart)   **Insight:** Confirms the
-- MAGIC stereotype: ultramarathon is dominated by 35–55 year-olds. Useful for
-- MAGIC sponsor demographic decks.

-- COMMAND ----------

SELECT FLOOR(athlete_age / 5) * 5 AS age_bucket,
       COUNT(*)                   AS n_finishes
FROM   marathos.gold.vw_results_enriched
WHERE  athlete_age BETWEEN 18 AND 80
GROUP  BY age_bucket
ORDER  BY age_bucket;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### D2. Gender split by decade
-- MAGIC **Viz:** Stacked bar chart (decade × gender), or twin-line for %women
-- MAGIC **Insight:** The most powerful diversity narrative in the dataset.
-- MAGIC Female participation in ultras has risen from ~5 % in the 1980s toward
-- MAGIC 25 %+ in the 2020s — this chart proves it numerically.

-- COMMAND ----------

SELECT
  FLOOR(event_year / 10) * 10                                  AS decade,
  SUM(CASE WHEN athlete_gender = 'M' THEN 1 ELSE 0 END)         AS men,
  SUM(CASE WHEN athlete_gender = 'W' THEN 1 ELSE 0 END)         AS women,
  ROUND(
    100.0 * SUM(CASE WHEN athlete_gender = 'W' THEN 1 ELSE 0 END)
    / NULLIF(COUNT(*), 0),
    1
  )                                                             AS pct_women
FROM   marathos.gold.vw_results_enriched
WHERE  athlete_gender IN ('M', 'W')
  AND  event_year IS NOT NULL
GROUP  BY decade
ORDER  BY decade;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### D3. Average finisher age over time
-- MAGIC **Viz:** Line chart   **Insight:** Is the sport "aging up"? A rising
-- MAGIC line means existing competitors are sticking around longer than new
-- MAGIC younger ones are joining — a recruitment concern. A flat or falling
-- MAGIC line means healthy generational turnover.

-- COMMAND ----------

SELECT event_year,
       ROUND(AVG(athlete_age), 1) AS avg_finisher_age
FROM   marathos.gold.vw_results_enriched
WHERE  athlete_age BETWEEN 18 AND 80
GROUP  BY event_year
ORDER  BY event_year;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Section E — Event profile
-- MAGIC
-- MAGIC The shape of the sport itself — what distances are popular, how speed
-- MAGIC scales with distance.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### E1. Distance-band participation mix
-- MAGIC **Viz:** Pie or donut chart   **Insight:** Where the volume lives.
-- MAGIC Most finishes happen at the "entry-level" 50–60 km band; the iconic
-- MAGIC 100 km / 100 mi events are a much smaller slice but get the headlines.

-- COMMAND ----------

SELECT
  CASE
    WHEN event_distance_km < 60   THEN '50-59 km'
    WHEN event_distance_km < 110  THEN '60-109 km'
    WHEN event_distance_km < 170  THEN '110-169 km (100mi range)'
    WHEN event_distance_km IS NOT NULL THEN '170+ km'
    ELSE NULL
  END  AS distance_band,
  CASE
    WHEN event_distance_km < 60   THEN 1
    WHEN event_distance_km < 110  THEN 2
    WHEN event_distance_km < 170  THEN 3
    WHEN event_distance_km IS NOT NULL THEN 4
    ELSE 99
  END  AS band_order,
  COUNT(*) AS n_finishes
FROM   marathos.gold.vw_results_enriched
WHERE  event_type = 'distance'
  AND  event_distance_km IS NOT NULL
GROUP  BY distance_band, band_order
ORDER  BY band_order;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### E2. Average speed by distance band
-- MAGIC **Viz:** Bar chart   **Insight:** The physiological cost of going long
-- MAGIC — speed drops sharply between 50 km and 100+ km. Quantifies "the wall."

-- COMMAND ----------

SELECT
  CASE
    WHEN event_distance_km < 60   THEN '50-59 km'
    WHEN event_distance_km < 110  THEN '60-109 km'
    WHEN event_distance_km < 170  THEN '110-169 km'
    ELSE '170+ km'
  END                                            AS distance_band,
  COUNT(*)                                       AS n_finishes,
  ROUND(AVG(athlete_average_speed), 2)           AS avg_speed_kmh,
  ROUND(PERCENTILE_APPROX(athlete_average_speed, 0.5), 2)
                                                  AS median_speed_kmh
FROM   marathos.gold.vw_results_enriched
WHERE  event_type = 'distance'
  AND  event_distance_km IS NOT NULL
  AND  athlete_average_speed IS NOT NULL
GROUP  BY distance_band
ORDER  BY MIN(event_distance_km);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### E3. Average speed per year (distance events)
-- MAGIC **Viz:** Line chart   **Insight:** Is the field getting faster? Rising
-- MAGIC line = better training/nutrition/shoes. A flatline through a decade
-- MAGIC + then a jump often correlates with a tech inflection (carbon-plate
-- MAGIC shoes c. 2018 is the textbook example in road running).

-- COMMAND ----------

SELECT event_year,
       ROUND(AVG(athlete_average_speed), 3) AS avg_speed_kmh
FROM   marathos.gold.vw_results_enriched
WHERE  event_type = 'distance'
  AND  athlete_average_speed IS NOT NULL
GROUP  BY event_year
ORDER  BY event_year;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### E4. Average distance covered in 24 h events, by year
-- MAGIC **Viz:** Line chart   **Insight:** The clearest single-axis measure of
-- MAGIC athletic improvement — fix the time, watch distance grow. Mirrors
-- MAGIC the world-record progression for 24 h running.

-- COMMAND ----------

SELECT event_year,
       ROUND(AVG(performance_distance_km), 2) AS avg_distance_km,
       ROUND(MAX(performance_distance_km), 2) AS max_distance_km
FROM   marathos.gold.vw_results_enriched
WHERE  event_distance_length = '24h'
  AND  performance_distance_km IS NOT NULL
GROUP  BY event_year
ORDER  BY event_year;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Section F — Performance & records
-- MAGIC
-- MAGIC The pointy end — fastest, longest, record progressions.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### F1. Top 10 fastest 100 km performances ever
-- MAGIC **Viz:** Table   **Insight:** The Marathos "wall of fame" for 100 km.
-- MAGIC Filtering on `99 <= distance <= 101` catches metric rounding variations
-- MAGIC in the source data.

-- COMMAND ----------

SELECT
  r.event_name,
  r.event_year,
  COALESCE(c.country_name, r.athlete_country) AS country,
  r.athlete_gender,
  r.athlete_age,
  ROUND(r.performance_time_seconds / 3600.0, 2) AS finish_hours
FROM   marathos.gold.vw_results_enriched r
LEFT JOIN marathos.gold.dim_country c
       ON r.athlete_country = c.country_code
WHERE  r.event_distance_km BETWEEN 99 AND 101
  AND  r.performance_time_seconds IS NOT NULL
ORDER  BY r.performance_time_seconds ASC
LIMIT  10;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### F2. Top 10 longest 24 h performances ever
-- MAGIC **Viz:** Table   **Insight:** The other "wall of fame" — extreme
-- MAGIC endurance over a fixed clock.

-- COMMAND ----------

SELECT
  r.event_name,
  r.event_year,
  COALESCE(c.country_name, r.athlete_country) AS country,
  r.athlete_gender,
  r.athlete_age,
  ROUND(r.performance_distance_km, 2)         AS distance_km
FROM   marathos.gold.vw_results_enriched r
LEFT JOIN marathos.gold.dim_country c
       ON r.athlete_country = c.country_code
WHERE  r.event_distance_length = '24h'
  AND  r.performance_distance_km IS NOT NULL
ORDER  BY r.performance_distance_km DESC
LIMIT  10;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### F3. 100 km record progression
-- MAGIC **Viz:** Step line chart   **Insight:** The running minimum of fastest
-- MAGIC time-known-to-date. A descending staircase that pinpoints record-breaking
-- MAGIC years. Visually compelling and a journalist-favourite chart.

-- COMMAND ----------

WITH yearly_best AS (
  SELECT event_year,
         MIN(performance_time_seconds) / 3600.0 AS year_best_hours
  FROM   marathos.gold.vw_results_enriched
  WHERE  event_distance_km BETWEEN 99 AND 101
    AND  performance_time_seconds IS NOT NULL
  GROUP  BY event_year
)
SELECT event_year,
       ROUND(year_best_hours, 2)                                       AS year_best_hours,
       ROUND(MIN(year_best_hours) OVER (ORDER BY event_year), 2)       AS world_record_to_date
FROM   yearly_best
ORDER  BY event_year;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### F4. Gender gap in speed — distance events
-- MAGIC **Viz:** Multi-series line chart (one series per gender) **or** table
-- MAGIC **Insight:** The gap between men's and women's average speed by decade.
-- MAGIC In ultramarathon (uniquely among endurance sports) the gap narrows
-- MAGIC noticeably with distance — this widget quantifies the trend over time.

-- COMMAND ----------

SELECT
  FLOOR(event_year / 10) * 10        AS decade,
  athlete_gender,
  COUNT(*)                            AS n_finishes,
  ROUND(AVG(athlete_average_speed), 3) AS avg_speed_kmh
FROM   marathos.gold.vw_results_enriched
WHERE  event_type = 'distance'
  AND  athlete_gender IN ('M', 'W')
  AND  athlete_average_speed IS NOT NULL
  AND  event_year IS NOT NULL
GROUP  BY decade, athlete_gender
ORDER  BY decade, athlete_gender;
